@startuml Agregación

class ConductorBus{
    -ropa
    -sombrero
    +usoRopa (ropa : ropa)
    +usoSombrero (sombrero : sombrero)
    +mostrar ()
}

class Ropa{
    -color
    -talla
    +mostrar ()
}


class Sombrero{
    -color
    -talla
    +mostrar ()
}

ConductorBus o-- Ropa
ConductorBus o-- Sombrero

@enduml
